### ISSUE TITLE
Node-red

### ISSUE THREAD

**Issue by drcosta89** [Garfonso/dlinkWebSocketClient#2]
Hello,
do you think it is possible to integrate this service on node red?
thank's for your job

**Comment by Garfonso** [comment]
Hi,

this is a library that can be easily added into all kinds of software. So somebode that knows how to add things to node-red can easily use this. But I don't know enough about node-red and this is also out of scope for this repository. So, sorry, you'll need to find somebody else.

Best regards,
Achim
