### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by joroMaser** [Garfonso/dlinkWebSocketClient#4]
I removed my Dlink from mydlink app , then I add back only to wifi then I closed the application

I have tried to run:
`node switch.js 192.168.1.11 <PIN_CODE> 1 0`

And I got 

```
Signed in!                                                                                                                 
Getting state                                                   
Had error: { Error: API Error 2: system error                    
    at WebSocketClient._getSetting (/mnt/dlink_websocketclient/index.js:282:27)   
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 2 }
```

What does it mean please?

If I make a wrong with PIN code I got:

```
Signed in!                                                                                                               
Getting state                                                                                                            
Had error: { Error: API Error 424: invalid device token                                                                  
    at WebSocketClient._getSetting (/mnt/dlink_websocketclient/index.js:282:27) 
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 403 }
```

**Comment by Garfonso** [comment]
Hi,

what device do you try to talk to?
Do you see a webpage on the IP?

**Comment by joroMaser** [comment]
@Garfonso I have edit my post , thank you

**Comment by Garfonso** [comment]
@joroMaser what device do you want to talk to? DSP-W118?

The device returns an error, when the library asks for the current state of the socket. 
You can try with a modified version of the switch.js file (which is meant as example anyway) and remove the client.state() call and see if it manages to switch the socket on or off.

**Comment by joroMaser** [comment]
@Garfonso 
Do you mean comment out the lines:
```
let state = await client.state();
console.log('Socket is ' + (state ? 'on' : 'off'));
``` 
in switch.js ?

I still got 


```
Had error: Error: API Error 2: system error   
    at WebSocketClient._setSetting (/mnt/dlink_websocketclient/index.js:263:19)       
    at process._tickCallback (internal/process/next_tick.js:68:7
```

**Comment by Garfonso** [comment]
> @Garfonso Do you mean comment out the lines:
> 
> ```
> let state = await client.state();
> console.log('Socket is ' + (state ? 'on' : 'off'));
> ```
> 
> in switch.js ?
> 

yes.


> I still got
> 
> ```
> Had error: Error: API Error 2: system error   
>     at WebSocketClient._setSetting (/mnt/dlink_websocketclient/index.js:263:19)       
>     at process._tickCallback (internal/process/next_tick.js:68:7
> ```

So it can not switch.
What device is this? (third time I ask... sorry.... without this information I can recommend nothing further)
